### ISSUE TITLE
"The external function `float64_broadcast_fmod' is not available"

### ISSUE THREAD

**Issue by mars0i** [ryanrhymes/owl#106]
I just downloaded the current master and built Owl using the suggestion in #104 about adding the openblas path for MacOS--thanks much for figuring that out.  I'm getting this error when I try to load Owl in utop:
```ocaml
# #require "owl";;
Error: The external function `float64_broadcast_fmod' is not available
```

In case it's helpful, I'll mention that maybe this could be related to an error I got when I tried to compile my code (that's why I figured I'd better try loading Owl by hand, first).  The error was on `new_mat.{i,j}` in this code, where `M` is from `module M = Owl.Mat` earlier in the same file:

```ocaml
let new_mat = M.empty height new_width in
... 
new_mat.{i,j} <- old_mat.{i, j*every}
```
Here's the error:
```File "src/lib/utils/genl.ml", line 210, characters 11-18:
Error: This expression has type
         M.mat =
           (float, Bigarray.float64_elt, Bigarray.c_layout)
           Bigarray.Genarray.t
       but an expression was expected of type ('a, 'b, 'c) Bigarray.Array2.t
make: *** [all] Error 1
```

**Comment by jzstark** [comment]
@mars0i  Not quite familiar with configurations on MacOS, but I was faced with a similar error before. One possible reason might be that, with the recent update of Owl  using `{}` to get elements from a matrix  is no longer available. Maybe you can try using `M.get` and `M.set` instead?

**Comment by mars0i** [comment]
Using `get` and `set` fixed the second problem.  That's good.  I still can't load Owl in utop with `#require"`, though.    That seems wierd--that I can compile but can't use it in utop.  `#list` shows
```
...
owl                 (version: dev)
owl_zoo             (version: dev)
...
```

**Comment by mars0i** [comment]
After I `#require "owl"` and get the `external function float64_broadcast_fmod is not available` error, I can successfully run `#show Owl` and `#show Owl.Mat`, but if I try to use `Owl.Mat` I get an error:
```ocaml
# Owl.Mat.create;;
Error: Reference to undefined global `Owl_dense_matrix'
```
Maybe this is something different.

**Comment by ryanrhymes** [comment]
> The error was on new_mat.{i,j} in this code, where M is from module M = Owl.Mat earlier in the same file: ...

Hi Marshall, the reason is that both Ndarray and Matrix are built atop of Genarray now. This change significantly simplified the internal design and reduced the code. The downside is we lost the capability of using `{i,j}` to index matrices. One solution is to use ppx which I am working on :)

> That's good. I still can't load Owl in utop with #require", though. That seems wierd--that I can compile but can't use it in utop.

The toplevel is now separated out from core library as part of zoo, it provides pretty printing. If you load owl_zoo, it will also automatically load owl. But you can also load owl separately without using zoo system.

> # #require "owl";; Error: The external function `float64_broadcast_fmod' is not available

How did you install Owl? Did you use `make install`? If so, you probably need to check where `dllowl_stubs.so` is installed? Try to do `find . -name *owl*.so` in your .opam folder. Because jbuilder calls `opam installer` and `opam installer` (ver 1.2 and so on) has a bug which will install .so file into stubslibs rather than stublibs. This also bothered me a lot when I ported to jbuilder. 

There are two solutions: one is upgrade opam to 2.0+beta4 which fixed this bug, or use `opam pin`. I haven't tested `opam pin` myself yet.

**Comment by mars0i** [comment]
> The downside is we lost the capability of using {i,j} to index matrices. One solution is to use ppx which I am working on :)
Well, `{i,j}` is nice, but using `get` and `set` is no problem.

> The toplevel is now separated out from core library as part of zoo, it provides pretty printing. If you load owl_zoo, it will also automatically load owl. But you can also load owl separately without using zoo system.
Ah, right.  That makes sense given the previous conversation with dbuenzli on another issue.  I'll use `owl_zoo`.

Yes, `make install`, and stubslibs was the problem. 
```
find . -name '*owl*.so' -ls
 49421799   1164 -rwx------   1  mabrams  staff     1188300 Aug 25 21:30 ./lib/stublibs/dllowl_stubs.so
 51975185   1320 -rwxr-xr-x   1  mabrams  staff     1349564 Sep 18 18:08 ./lib/stubslibs/dllowl_stubs.so
```
 I moved the new `dllowl_stubs.so` into stublibs and everything seems to work now.  Great.  Thanks.  I was using 2.0-beta3 and just switched back to 1.2, but maybe I'll just go to 2.0-beta4.
