### ISSUE TITLE
Make dense matrices/arrays central

### ISSUE THREAD

**Issue by bluddy** [ryanrhymes/owl#122]
Currently, we don't find Matrix or Ndarray as a top module. Instead, I have to constantly remember to navigate to Dense first. I think 90% of the time, people want to use dense matrices, so why not make the default matrix dense, and have a Sparse hierarchy as an option? It'll simplify what is already quite a deep module tree.

**Comment by mars0i** [comment]
@bluddy you might know this, but if one only needs double-precision floats, `Owl.Mat` is an alias for `Owl.Dense.Matrix.D`.  That's what I usually use.  And `Arr` is an alias for `Dense.Ndarray.D`.  (https://github.com/ryanrhymes/owl/wiki/Tutorial:-Basic-Data-Types)

Maybe this should be a different issue), but perhaps it's related:  It might be confusing to an Owl newbie that the main documentation comments for basic matrix operations are in the [`Owl_dense_matrix_generic` documentation](http://www.cl.cam.ac.uk/%7Elw525/owl/Owl_dense_matrix_generic/index.html).  `Owl_dense_ndarray_generic` is similar.  I don't think there's anything that points to these pages.  Maybe this is partly due to ocamldoc limitations?

**Comment by ryanrhymes** [comment]
Because OCaml is rather weak in managing namespace, I prefer to use a more self-explained and structural naming scheme to avoid polluting the top namespace. I have already made some aliases for frequently used modules as Marshall pointed out. In case you more often use other modules, you can make your own alias such as `module F32 = Dense.Ndarray.S`.

**Comment by ryanrhymes** [comment]
I added this `#require "owl_top";; open Owl;;` into my .ocamlinit file so I don't have to load Owl manually every time when I start utop, it also automatically opens Owl module so I can use `Mat` and `Arr` directly.
