### ISSUE TITLE
Toplevel error requiring "owl"

### ISSUE THREAD

**Issue by porcow** [ryanrhymes/owl#127]
Installed Owl from source, I was trying to require "owl" in toplevel(utop), and came across such an error as follows:
`utop # #require "owl";;`
`Error: The external function 'complex64_div_scalar' is not available`

If anyone comes across similar error I would like to discuss about it. Thank you.

OS: macOS Sierra 10.12.6
OCaml: 4.05.0
OPAM: 1.2.2
jbuilder: 1.0+beta16
utop: 2.0.1

**Comment by jzstark** [comment]
Hi @porcow,  just to make things clear: what OS / OCaml / OPAM version do you use?  I tend to follow the steps in [Dockerfile](https://github.com/ryanrhymes/owl/blob/master/Dockerfile) whenever possible, so for example I use Ubuntu 16.04, OCaml 4.04.0, and OPAM 2.0.0-beta4.

**Comment by ryanrhymes** [comment]
Does this relate to the OPAM issue we discussed before? https://github.com/ocaml/opam/commit/718d6198e338069852dcdde067f56df236235370#diff-5508a1f41811a003b062a9d606062507

Please can you have a look if OPAM copied the Owl's lib file to stubslibs rather than stublibs? In that case, you need to either upgrade to OPAM 2 beta4 at least, or copy it back to stublibs manually.

**Comment by porcow** [comment]
OPAM copied the Owl's lib file to stubslibs rather than stublibs, I copied it back to sublibs, it works.

**Comment by ryanrhymes** [comment]
OPAM beta 4 fixed this issue, and OPAM beta 5 has been recently released.
