### ISSUE TITLE
Fatal error: unknown C primitive

### ISSUE THREAD

**Issue by ryanrhymes** [ryanrhymes/owl#168]
@jzstark I tried your recent #165 PR on the lab caelum machine. It compiles fine, but whenever if I try to run any neural network zoo script, it errors with the following message:

```bash
Fatal error: unknown C primitive `stub_float64_ndarray_avgpool_cuboid_backward_bytecode'
```

The configuration of the lab machine is : 

```bash
Linux caelum-204 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

@jzstark Can you investigate and solve this issue? Thanks.

**Comment by jzstark** [comment]
Could it be that the `dllowl_stub.so` file on the lab machine is actually installed in the `stubslibs` directory rather than `stublibs`? I use a docker container from 3 days ago, and within it I try to compile and install the newest code, and it shows the same error message when I start the `utop`. Its reason is the wrong location of `dllowl_stub.so` file, so I was wondering if the lab machine has the same problem.

**Comment by ryanrhymes** [comment]
@jzstark  I figured it out, not only opam's bug but also flto thing. The lab's machine also has problem in support lto option.
