### ISSUE TITLE
infix operators

### ISSUE THREAD

**Issue by nilsbecker** [ryanrhymes/owl#21]
hi, some comments about the infix operators:

`@@` overlaps with the builtin application `f @@ g x == f (g x)` which i think may be a bit intrusive?

precedence: 
https://caml.inria.fr/pub/docs/manual-ocaml/expr.html
i think `$@` for dot product has lower precedence than summation which it probably should not have. you probably want something that starts with `*` or `%` for instance `*.@`. there may be other precedence issues, not sure.

why are there `/$` and `$/` both? actually, i suspect that all of the `$...` combinations are problematic wrt precedence?

finally, one could think of adding prefix operators for negative and inverse? e.g. `~-@` and `~/@`.

generally, how will this work out when vectors also enter the picture? will there be a symbol do denote vector-vector operations and another one for matrix-vector? i suspect modular implicits would allow overloading those, but is it even sure that they will come?

**Comment by ryanrhymes** [comment]
Modular implicits will certainly be the best solution whenever it is included in the official OCaml release. I don't know when it will happen eventually.

Overloading (if there is any in OCaml) infix is a pain in general. Your proposal (especially $@) makes sense since OCaml decides the precedence based on the first character of the infix operator. At the moment, I would recommend only locally open a module and explicitly use parentheses if you want to use those infix operators.

My currently plan is: there is an underlying layer to operate on native OCaml types (float, bigarray ...) then wrap them up in Owl_Ext module so they can interoperate different number types. Currently, there is only very limited support, but you can give it a try using master branch.

```ocaml
open Owl_ext;;
let a = F 2.5;;
let b = C Complex.({re=1.; im=2.});;
let x = Owl_ext_dense_matrix_z.sequential 3 3;;
let y = Owl_ext_dense_matrix_d.uniform 3 3;;
x + y;;
a * y;;
...
```

Note this module is not finished yet, but the infix will be redesigned in this module. Vector module is also working in progress, and it mostly serves Algodiff module to do algorithmic differentiation.

**Comment by nilsbecker** [comment]
oh, ok that is some pretty low-level stuff. i was going to check what the types are but opam failed to install owl:
```
# File "lib/owl_dense_common.ml", line 108, characters 108-129:
# Error: Unbound module Lacaml_common
# Hint: Did you mean Lacaml__common?
```
...

**Comment by ryanrhymes** [comment]
I guess this is because the recent update of Lacaml changes its internal module names. Anyway you cannot test the example above if you use opam to install. You can use our docker image to try, or wait until the end of this week so I can publish a new release on opam. The new release will not have lacaml dependency any longer.

**Comment by nilsbecker** [comment]
no worries, i can do it then. interesting that you move away from lacaml - what is replacing it for you?

**Comment by mars0i** [comment]
Now that there's been a change, ....  :-)  Very much enjoying using Owl btw.  I didn't follow everything in the discussion above, but fwiw, I'm not sure I like having +, -, *, and / be the default infix matrix operators for elementwise arithmetic (or for anything).  That means that several additional characters are required in one way or another just so I can use a single infix operator a single time in  a function that also uses standard integer infixes.(Still a newbie, so correct me if I'm wrong.) This partly defeats the purpose of an infix in such a case.  The old Owl infix definitions didn't have the same consequence.  Alternatively I can use the prefix operator, but ... one of the things that attracted me to OCaml instead of Clojure--what I'd been using--is that prefix functions make complex equations difficult to read.  I guess an alternative is to just define my own infix operators, but it's preferable to follow a standard syntax.  I recognize there are a lot of tradeoffs here, and I don't expect I'll ever be one of the heaviest users, so I'm not saying that it's wrong to use the one-character arithmetic operators for matrix arithmetic, and I'll understand if Owl keeps the current definitions for elementwise infixes.  Just wanted to raise these points on the chance that it could be helpful for them to be raised.

**Comment by nilsbecker** [comment]
i'm also not sure what to think about the `Ext` module. 

it allows overloading the usual arithmetic operators (requiring to wrap scalars etc.), which is nice, and can make code much more readable. 

on the other hand, i feel this is partly a step back into the untyped way of doing things. i.e. everything is wrapped into one big number/matrix/whatever type, and while the underlying functions know how to deal with it due to matching on the constructors, an "external" user of the library can no longer deduce from the type that a value returned from a function was a matrix (vs. a scalar); it's all just the wrapper type. 

iiuc, the Ext module is meant for prototyping, where maybe such tight-typing concerns are secondary. this could be a valid point. in any case for "production" code i would be happier with something a little more verbose but with more meaningful types. and there is a risk of creating a two-languages problem (within one language...) where switching from prototype to production requires rewriting. 

i could be overthinking/misinterpreting this, though..

**Comment by ryanrhymes** [comment]
Hi, thanks for raising this interesting discussion. First of all, there is no such absolutely correct solution but more about a design decision which I can briefly talk about in this thread.

There is no overloading in OCaml atm which already indicates operator design will be difficult. I am leaning more towards readability when designing Owl. `Ext` module is included for two reasons: (1) fast prototyping, most of the time, we just want to open `utop` and experiment some ideas. `Ext` is for that. (2) `Ext` is the preparation for modular implicits, whenever it is included in OCaml official release, `Ext` can be quickly modified to adapt modular implicits, in which case we will have the best of both worlds, type checking and operator overloading.

Each operator corresponds to one specific function implemented in Owl. You can always choose to call the function directly without using operators for performance and type checking. Operators are not going to replace those functions, so you can decide how and when to use them. 

There are several things might be helpful:

1) operators are defined in this functor: [operator](https://github.com/ryanrhymes/owl/blob/master/lib/owl_operator.ml). By modifying this file, you can redefine all the operators in Owl except those in `Ext`. This requires you to hack into Owl but it is really straightforward.

2) if you don't want to use operators at all, you can include `Owl_dense_matrix_s` instead `Owl.Dense.Matrix.S`; the previous one does not include operators. The same applies to other modules such as `Owl_dense_ndarray_d` and `Owl.Dense.Ndarray.D` ....

3) You can choose to open a module locally to avoid conflicts. Or, what I prefer using this:
```ocaml
module M = Dense.Matrix.S
....
M.(x + y >. 0.5)

```
M.(......) grammar gives you capability to use operator without messing up with OCaml's native operators. All in all, opening a module globally needs great care. E.g., `Mat.sin`, `Mat.cos` ... these functions can also conflicts with those in `Pervasives` module.

All in all, operators are optional and they are not meant to replace any functions in Owl.  You can actually redefine them if necessary. Nothing is fixed at the moment, as we accumulate more and more feedback, things will improve, hopefully :)

**Comment by mars0i** [comment]
Thanks for the detailed explanation, and for noting a variety of options.  I had not understood that opening Ext allows overloading.  That's very nice.  I personally like overloading--one of the things I miss from SML--but I understand why OCaml avoids it for the reasons that nilsbecker expressed.

I think the M.(...) notation is probably OK from my point of view for me when matrix calculations are complex.  

Instead of hacking operators.ml, another option is simply to define one's own aliases for particular operators using e.g. `let (+$) = M.(+)`, or more directly `let (+$) = M.add`.  Since many ml files won't use many operators, this might not be a bad option, and it documents the operators explicitly within the file.

(After opening `Owl` and aliasing `M` to `Dense.Matrix.S`, where is the `+$` in your example coming from?  I get an error from that.  Maybe a typo using the old notation--should be `+`?    I get an error from `>.`, too.

**Comment by ryanrhymes** [comment]
> Instead of hacking operators.ml, another option is simply to define one's own aliases for particular operators using e.g. `let (+$) = M.(+)`, or more directly `let (+$) = M.add`.  Since many ml files won't use many operators, this might not be a bad option.

Indeed.

> (After opening `Owl` and aliasing `M` to `Dense.Matrix.S`, where is the `+$` in your example coming from?  I get an error from that.  Is that a typo--should be `+`?   

Probably because you installed Owl using OPAM, `+$` is currently in master branch and will appear in the next release. `+$` is for adding a matrix with a scalar. 

>  I get an error from `>.`, too. 

Sorry it was a typo, it should be `>.$` which is for element-wise comparison of a matrix/array to a scalar value. In `Ext` module, you can drop `$` and simply use `+` and `>.` since it allows interoperation between different numbers. [This tutorial](https://github.com/ryanrhymes/owl/wiki/Tutorial:-Operators-and-Ext-Module) might be helpful.
