### ISSUE TITLE
ticks of axis 

### ISSUE THREAD

**Issue by zoggy** [ryanrhymes/owl#25]
Is it possible to set the ticks of x axis ? I'd like to print Jan, Feb, Mar, ... and so on instead of the automatic 0 2 4 ....

**Comment by hcarty** [comment]
This is possible in PLplot using either [Plplot.Plot.axes](https://github.com/hcarty/ocaml-plplot/blob/master/src/plplot.mli#L249) or [Plplot.plslabelfunc](https://github.com/hcarty/ocaml-plplot/blob/master/src/plplot.mli#L1056).  Owl may need some modification to integrate this properly but the underlying support is there.

**Comment by zoggy** [comment]
Thanks ! Indeed the underlying structure is abstract in Owl :-/

**Comment by ryanrhymes** [comment]
@zoggy Definitely an important function, I added it. I hope the following code will work for you for the time being. It is only in the master branch and not in the OPAM release yet.

```ocaml
let x = Vec.sequential 4;;
let y = Vec.uniform 4;;
let h = Plot.create "labeltest.pdf";;
Plot.plot ~h x y;;
Plot.set_xticklabels h [0.;1.;2.;3.] ["Jan"; "Feb"; "Mar"; "Apr"];;
Plot.output h;;
```

**Comment by ryanrhymes** [comment]
`Plot` module is actually quite straightforward. All the information of a page is saved in a record (of type `page`). All the operations you have done on a page will be cached in a list `page.plots`. Whenever you call `output` function, `Plot` module will call `_initialise`, `_prepare_page`, `_finalise` these three functions to actually finish "drawing" your plot then output.

**Comment by zoggy** [comment]
Thanks.  I had to opam pin to master branch of eigen too but no problem. 

`Plot.set_xticklabels` works, except that some labels do not appear; I though this was a question of missing space and reduced the font size, but no. Is there something more to do ?

**Comment by ryanrhymes** [comment]
I guess this is because currently Owl only draws at the major ticks, the reason is `plslabelfunc` calls the callback function whenever it encounters the major ticks. @hcarty should know more about how to customise the ticks in Plplot.

**Comment by hcarty** [comment]
First an API suggestion: maybe the `Plot.set_*ticklabels` function should take a list of `(value : float, label : string)` tuples?  That will guarantee that a user can't accidentally pass in lists of mismatched lengths.

Second, regarding tick spacing and labeling - there is detection logic in the C core of PLplot which handles this.  I don't recall the details - it's been a while since I hacked on that code - but it is possible to manually specify the major (`plsmaj`) and minor (`plsmin`) tick spacing.  IIRC all major ticks are labeled by default.

**Comment by ryanrhymes** [comment]
The API suggestion is really nice. I have changed it.
