### ISSUE TITLE
Matrix multiplication

### ISSUE THREAD

**Issue by priamfive** [ryanrhymes/owl#44]
I've been enjoying playing around with owl - thank you very much for creating. When experimenting I've noticed that  matrix multiplication is quite slow for large matrices. For example if I create two random 5000x5000 matrices using Mat.uniform then multiply together it takes just under two minutes. If I do the same with Julia it takes just under two seconds (both owl and Julia on bash on Ubuntu on windows). Any obvious reason for this?

One other minor comment: it would be useful to put Mat. of_array command more prominently in the documentation as it is handy for creating small matrices.

**Comment by ryanrhymes** [comment]
Hi @priamfive , thanks for trying out Owl 👍 

> When experimenting I've noticed that matrix multiplication is quite slow for large matrices. For example if I create two random 5000x5000 matrices using Mat.uniform then multiply together it takes just under two minutes. If I do the same with Julia it takes just under two seconds (both owl and Julia on bash on Ubuntu on windows). Any obvious reason for this?

I just did a simple test on my MacBook (1.1 GHz Intel Core m3). For Owl, I used the following code snippet 
```ocaml
let test () = 
  let t = Unix.gettimeofday () in
  Mat.(x *@ y) |> ignore;
  Unix.gettimeofday () -. t
```

For Julia, I used the following code snippet 
```julia
function f10()
  x = rand(5000,5000)
  y = rand(5000,5000)
  t0 = time()
  x * y
  t1 = time()
  @printf "x * y:\t\t%.8f\n" (t1 -t0)
end
```

I ran 5 tests and took the average, the results showed that Owl used 4.975s and Julia used 4.938s. My MacBook is not very fast anyway. Both have similar performance because both called the same underlying BLAS library. 

I don't have a very clear answer about why Owl is so slow on your machine. But I suspect Julia and Owl called different underlying BLAS implementations on your machine. Similar thing happened before in one of my previous experiment on lab cluster, the node in the cluster is much faster than my macbook but the same matrix multiplication can take over 147s. The reason originated from the underlying BLAS library. 

Have you tried to do the same experiment for both Owl and Julia using Owl's docker image? Do they have different performance? https://hub.docker.com/r/ryanrhymes/owl/

I can investigate a bit deeper next week to see how to control owl's linking to underlying BLAS. Atm, I think this is useful: https://github.com/mmottl/lacaml/issues/29

**Comment by ryanrhymes** [comment]
> One other minor comment: it would be useful to put Mat. of_array command more prominently in the documentation as it is handy for creating small matrices.

Yes, the documentation lags behind the development quite a lot. I will starting writing another more comprehensive guide very soon.

**Comment by superbobry** [comment]
As a slight offtopic: I wonder if we can use [mkl](https://software.intel.com/en-us/mkl-developer-reference-c-blas-and-sparse-blas-routines?language=ru) for BLAS operations? AFAIK there is no readily available package for OCaml, but that could be a good contribution to the ecosystem.

**Comment by priamfive** [comment]
The problem does indeed seem to be the different versions of blas. Julia appears to ship with Openblas. When I downloaded Openblas and edited the oasis file for Owl to pick it up as suggested in the lacaml link you provided, I obtained similar performance from Julia and Owl (at least when the test is compiled, it is still slow if run from utop). 

Thank you for all your work on Owl - it seems very promising.

**Comment by ryanrhymes** [comment]
@priamfive it's great you sorted it out. I guess you might also count the time spent in `Mat.uniform`, which explains why the compiled version (in native code?) has comparable performance to Julia, because `Mat.uniform` is implemented in pure OCaml. In the end, I will redo this function in C.

Btw, compiling into native code often gives much better performance, but I guess you already did so  :)

**Comment by ryanrhymes** [comment]
> As a slight offtopic: I wonder if we can use mkl for BLAS operations? AFAIK there is no readily available package for OCaml, but that could be a good contribution to the ecosystem.

@superbobry indeed, I think it is absolutely valuable to have MKL as one of Owl's backends. MKL has very good performance on Intel platform. I have put this on Owl's todo, many thanks for the suggestion. 👍

**Comment by ryanrhymes** [comment]
In the end, I decide to focus on OpenBLAS backend since it provides really good performance in many use cases. Currently I am trying to minimise Owl's dependency to make building and deployment easier. I will close it, but it does not mean I won't introduce MKL as an option in future. Thanks again for the advice.
