### ISSUE TITLE
float versions of combinatorial functions?

### ISSUE THREAD

**Issue by mars0i** [ryanrhymes/owl#45]
I found that `Math.combination` gives odd results when the first argument is large, but realized that this is probably expected from the conversion to OCaml ints.   My problem was solved by seeing that `combination` wraps `Gsl.Sf.choose` and using the latter instead.  The result will get multiplied by a float, anyway, so using the GSL function is better.  (It's good that I experienced the problem, or I would have continued to convert the int output of `combination` back to a float!)

This made me wonder whether it would be worth including float versions of `combination` in `Owl.Maths`.  I don't know the overall goals of the module, and I now know how to call GSL directly, so I don't have to have a float version of `combination` in `Maths`, but I thought I'd raise the question.

(My use case: In population genetics, a Wright-Fisher model of the evolution of a population uses binomially distributed transition probabilities from one state of the population, in which there are *i* copies of a gene, to a state with *j* copies.  This means that a transition matrix for a population of *N* organisms with up to 2*N* copies of a gene needs to compute combinations in which 2*N*+1 is the upper term.  That produces some large numbers for even a small population of reasonable size.)

(I hope I'm not being annoying with too many minor issues and questions.)

**Comment by ryanrhymes** [comment]
Marshall thanks for pointing out this issue. The reason is on 64-bit platform the range of OCaml `int` is limited by `max_int` (4611686018427387903) whereas `float` is by `max_float` (1.79769313486231571e+308) which has a much larger range. 

I think it makes sense to make a float version, so I have added `Maths.combination_float`. Please do open an issue in case you identify any bug, really appreciate it.

**Comment by mars0i** [comment]
Great--thanks.  I'll use that instead of calling GSL directly.
