### ISSUE TITLE
GSL vs. Cephes

### ISSUE THREAD

**Issue by superbobry** [ryanrhymes/owl#5]
Have you considered swapping GSL for Cephes? It lacks some functionality compared to GSL, but is available under a much less restrictive license, see [SciPy repo](https://github.com/scipy/scipy/tree/master/scipy/special).

**Comment by superbobry** [comment]
Another point regarding this: do you think it's okay to link with GPL-licensed GSL and have an MIT license?

**Comment by ryanrhymes** [comment]
Honestly, I do not actually know. I need to ask some copyright experts in the lab later this week, it is on my todo list. But IMO, this should be addressable :)

**Comment by ivg** [comment]
> Another point regarding this: do you think it's okay to link with GPL-licensed GSL and have an MIT license?

IANAL, but you can't. Only GPL licensed program can be linked with the GPL code. So, if OWL will switch to GSL, it needs to be relicensed under the GPL license. Thus, any other project, that would like to use it, also needs to be relicensed. It is like a plague. In particular, I would be able to use OWL anymore, if it will switch to GSL, cause my project has a liberal MIT license.

**Comment by superbobry** [comment]
Thanks for confirming my suspicions @ivg. 

By the way, @rleonid did a [wrapper](https://github.com/rleonid/ocephes/blob/master/src/lib/ocephes.mli) around some of the Cephes functions. @ryanrhymes do you think we can build on that?

**Comment by ivg** [comment]
The bad news, is that you're already distributing a GPL-3.0 derived library under an incompatible license, thus breaking the GPL license agreement. Legally, this means, that your license to use GSL is revoked and you need to reobtain it by contacting the GSL and asking them to forgive you. This is legally, in real life if you fix the problem promptly nobody will usually hunt you for the mistake. However, serious commercial companies might consider this historic event to taint the legal history of an application, and advice not to use it, to prevent possible legal problems. 

The problem can be rectified without any legal aftertaste if you remove any GSL dependency, and release a new version, that will be clean MIT. However, it might be possible that it is either (1) inconvenient or impossible. For example, if some functionality is only available in GSL, or, if it will require a substantial rewrite of the library. 

So, if you can't get rid of GSL, then you can try to split your library into two or more components. Some, that are pure MIT, and those that depend on GSL. You need distribute them differently (not necessary in different repositories, you can have a LICENSE file that applies different licenses to different subfolders, files, etc). Now, a library user will be able to either stick to a non-GPL'ed components, or to use the GPL (and thus relicense its application). Btw, GSL is licensed under the GPLv3, so in order to use, owl should be licensed under GPLv3 or AGPLv3 terms.  Licensing owl under GPLv3 or AGPLv3 will have considerable ramifications, to name a few: to use owl an application must be relicensed under the GPLv3, the latter is prohibited in many organizations and distribution platforms, e.g., Google Play, Appstore, are not accepting GPL software. Linux kernel neither (not our case, of course). The GPLv3 license is broken and hampers the distribution of the software in a modern mobile world.

**Comment by rleonid** [comment]
After some off-github discussions (with @smondet) it may not be as bad as @ivg makes it sound. The project itself may be compatible per https://www.gnu.org/licenses/license-list.html#Expat, but using it downstream would still require following GPL.

**Comment by ivg** [comment]
> The project itself may be compatible per https://www.gnu.org/licenses/license-list.html#Expat, but using it downstream would still require following GPL.

Even if it was possible, it would still defeat the whole purpose of Expat (aka MIT). What is the purpose of licensing a library under a non-copyleft license, if you are still requiring a user to follow GPL? 

> it may not be as bad as @ivg makes it sound

I didn't make it sound bad, it is bad, sorry. Not the owl story (it is still fixable), but the whole GPL story. That's why we spent hundreds of thousands of dollars and several years to get rid of any GPLed software in our codebase. 

Let me put it more simple, GPL license states, that when you combine your program, with a GPL program, either via linking (static or dynamic), or via copying the code (with and without the modification), you're creating a combined work, that should be licensed under the GPL or AGPL and nothing else (the no sublicensing clause). 

When you're combining several pieces of code, and some of them are GPL, while some are not, then you need to check their compatibility. The compatibility of a license A with GPL means, that you can combine the code, distributed under the license A with GPL, and release the combined work as GPL. 

The examples of licenses that are not compatible with GPLv3: proprietary, GPLv2, LGPLv2, Apache2. For example, Linux kernel cannot use/copy any GPLv3 code. Note, that OCaml itself is distributed under the LGPLv2 library, that is incompatible with the GPLv3. You can still link with the OCaml standard library, under the "Standard Library" exemption. However, the compiler-libs library doesn't fall (to my opinion) into this exemption, thus any code that depends on it (a majority of ppx rewriters) can't be linked with a program that links with gsl (or at least such program can't be distributed). 

Now let's focus on the OWL. According to the build specification, the OWL library links with GSL library, that is distributed under the GPLv3 license. Given that all other external dependencies are obtained under compatible licenses, the OWL library is a combined work, that can be distributed only under the GPL or AGPL license. 

Currently, you're distributing the combined work under the MIT license (aka Expat, aka ISC), that means, that, in fact, you have sublicensed the GSL, thus breaking the terms of the GPLv3 license. That means, that your license to use GSL is temporary voided. In GPLv3, you can get it back as soon as you fix the violation (given that in 60 days before or after the fix the copyright owner didn't revoke the license permanently). The fix would be either to release the OWL library under the GPLv3/AGPLv3, to remove the dependency on GSL, or to factor out the section of a library that doesn't depend on GSL into a separate library, distributed under the MIT license. The GSL dependent part should be distributed as a separate library under the GPL license. Given the last solution, the end user may opt to use only the MIT part of the library, without infecting the derived work with GPL, or a user may decide to use the GSL library, and either does not distribute his program or distribute it under the GPL license.

**Comment by ryanrhymes** [comment]
Thanks for all the inputs, now Owl has a very small dependency and does not rely on GSL any longer. It takes a bit long to achieve this but luckily it is done in the end :)

**Comment by ivg** [comment]
Thanks a lot, great news!
