### ISSUE TITLE
inverse on non-square matrix aborts utop

### ISSUE THREAD

**Issue by mars0i** [ryanrhymes/owl#79]
Passing a non-square matrix to `inv` aborts utop in addition to the assert failure.

```
Welcome to utop version 2.0.1 (using OCaml version 4.04.2)
...
# Owl.Mat.inv (Owl.Mat.sequential 2 3);;
Assertion failed: (rows() == cols()), function inverse, file ./Eigen/src/LU/InverseImpl.h, line 338.
Abort trap: 6
~$
```
I used the latest version of the master branch of Owl with the version of the OCaml Eigen lib currently available in opam for OCaml 4.04.2:

```
~$ opam list | grep -i eigen
eigen                           0.0.4  Owl's OCaml interface to Eigen3 C++ libra
```
Let me know if you need other info about my configuration.  Thanks-

**Comment by ryanrhymes** [comment]
Yes, `inv` only accepts square matrices as inputs. I recommend to use the `inv` function in `Linalg` module rather than the one in `Dense.Matrix` module for large matrices.

For rectangular matrices, you can use `pinv` function in `Linalg` module, as you already mentioned in https://github.com/ryanrhymes/owl/issues/77

**Comment by mars0i** [comment]
Yes, I wouldn't expect `inv` to work with square matrices.  I wasn't thinking when I gave it a rectangular matrix.  Just wanted to report the utop crash.  Thanks.

**Comment by ryanrhymes** [comment]
This has been fixed now :)

**Comment by mars0i** [comment]
Great--thanks.
