### ISSUE TITLE
Hypothesis testing

### ISSUE THREAD

**Issue by superbobry** [ryanrhymes/owl#8]
Could you list the tests which are yet to be implemented? 

I have some tests implemented in [pareto](https://github.com/superbobry/pareto/blob/master/lib/tests.mli), maybe some of that could be useful for owl as well.

**Comment by ryanrhymes** [comment]
Hi Sergei, that would be awesome! I currently implemented: z-test, t-test (one sample, paried, unpaired), Jarque-Bera test, Chi-square variance test, and runs test.

I still need (you can certainly add more :) -- f-test; Kolmogorov-Smirnov test; Anderson-Darling test; Durbin-Watson test; Fisher's exact test; Lilliefors test; sign test, and so on. I saw several have been implemented already in Pareto!

Actually, if you have a look at this page: [Matlab hypothesis test](https://uk.mathworks.com/help/stats/hypothesis-tests-1.html), there are distribution, location, and dispersion tests (with detailed functions listed if you click each category). My goal is to cover all of them in the end.

Another thing: currently, the return of a test is a 3-tuple: (reject or not, p-value, score). In the end, the return should also include confidence interval, and return in a record type (type test_result which is actually already int the code if you look at owl_stats.ml).

**Comment by superbobry** [comment]
Hi Ryan, I am happy to say we are (finally) going to tackle this with @bagmanas in the following couple of month. 

I would like to come up with an acceptance criteria for the implemented tests. Should we cross-check against R, Matlab/Octave or SciPy? My previous experience suggest that all three could differ in the way the compute things. If that is the case, which side should we take? By the way, I've looked through the tests already implemented in Owl and it seems there're no unit tests for them. Should we write some for the new tests?

**Comment by ryanrhymes** [comment]
Hi Sergei, that's great if you and  @bagmanas can help in stats module. 

For cross-validate, I often use Matlab and R. But I think either is fine as long as you specify that in the (in-line) document so that others can know which has been tested against. You probably know R and Matlab better than me so you can decide.

For API design, I am using a mixture of all three at the moment in Owl (try to get the best of all worlds). I think the API in your Pareto library is very nice so I am already happy if you just use the similar style. Of course, if you have even better design, always welcome :)

You are right. I did not write any unit tests for Stats module at the moment, mostly because the module is far from complete. But after you reshape the current hypothesis tests and put more tests, we should start writing unit tests.
